#!/usr/bin/env bash
#Bash script that displays lines containing the bash word
#You cannot use pgrep
#The third line of your script must be # shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
